/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FindSum */

#ifndef _Included_FindSum
#define _Included_FindSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FindSum
 * Method:    totalSum
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_FindSum_totalSum
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
